name: Add issues to projects

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.0.5
        with:
          project-url: https://github.com/azerothcore/azerothcore-wotlk/projects/14
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: 1-19
